apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: editor
  annotations:
    kubernetes.io/display-name: Editor
    kubernetes.io/description: "Edit access to all Datum Cloud resources in the organization, except managing team members"
    taxonomy.miloapis.com/sort-order: "15"
    taxonomy.miloapis.com/product: "Access Everything"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: viewer
      namespace: datum-cloud
    - name: core-admin
      namespace: milo-system
    - name: networking.datumapis.com-admin
      namespace: milo-system
    - name: telemetry.miloapis.com-admin
      namespace: milo-system
    - name: resourcemanager.miloapis.com-project-admin
      namespace: milo-system
    - name: resourcemanager.miloapis.com-organization-viewer
      namespace: milo-system
