apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: viewer
  annotations:
    kubernetes.io/display-name: Viewer
    kubernetes.io/description: "View access to all Datum Cloud resources in the organization"
    taxonomy.miloapis.com/sort-order: "20"
    taxonomy.miloapis.com/product: "Access Everything"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: networking.datumapis.com-viewer
      namespace: milo-system
    - name: telemetry.miloapis.com-viewer
      namespace: milo-system
    - name: quota.miloapis.com-organization-quota-manager
      namespace: milo-system
    - name: resourcemanager.miloapis.com-organization-viewer
      namespace: milo-system
    - name: resourcemanager.miloapis.com-project-viewer
      namespace: milo-system
