apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - platforminvitation-emailtemplate.yaml
  - userapproved-emailtemplate.yaml
  - userinvitation-emailtemplate.yaml
  - userrejected-emailtemplate.yaml
  - userwaitlist-emailtemplate.yaml
  - userwelcome-emailtemplate.yaml
