apiVersion: notification.miloapis.com/v1alpha1
kind: EmailTemplate
metadata:
  name: emailtemplates.notification.miloapis.com-userapprovedemailtemplate
spec:
  subject: "ğŸš€ You're in! Your access to Datum is here ğŸš€"
  htmlBody: |
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html dir="ltr" lang="en">
      <head>
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/logo-datum-light.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-gh.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-li.png" />
        <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
        <meta name="x-apple-disable-message-reformatting" />
        <style>
          @font-face {
            font-family: 'Alliance No1';
            font-style: normal;
            font-weight: 600;
            mso-font-alt: 'sans-serif';
            src: url(https://www.datum.net/fonts/datum/allianceno1-semibold-webfont.woff2) format('woff2');
          }
    
          * {
            font-family: 'Alliance No1', sans-serif;
          }
        </style>
        <style>
          @font-face {
            font-family: 'Alliance No1';
            font-style: normal;
            font-weight: 500;
            mso-font-alt: 'sans-serif';
            src: url(https://www.datum.net/fonts/datum/allianceno1-medium-webfont.woff2) format('woff2');
          }
    
          * {
            font-family: 'Alliance No1', sans-serif;
          }
        </style>
        <style>
          @font-face {
            font-family: 'Alliance No1';
            font-style: normal;
            font-weight: 400;
            mso-font-alt: 'sans-serif';
            src: url(https://www.datum.net/fonts/datum/allianceno1-regular-webfont.woff2) format('woff2');
          }
    
          * {
            font-family: 'Alliance No1', sans-serif;
          }
        </style>
      </head>
      <body
        style="margin-left:auto;margin-right:auto;margin-top:auto;margin-bottom:auto;background-color:rgb(255,255,255);font-family:&#x27;Alliance No1&#x27;, ui-sans-serif, system-ui, sans-serif, &#x27;Apple Color Emoji&#x27;, &#x27;Segoe UI Emoji&#x27;, &#x27;Segoe UI Symbol&#x27;, &#x27;Noto Color Emoji&#x27;">
        <!--$--><!--html--><!--head-->
        <div
          style="display:none;overflow:hidden;line-height:1px;opacity:0;max-height:0;max-width:0"
          data-skip-in-text="true">
          Your account has been approved
          <div>
            Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿Â â€Œâ€‹â€â€â€ï»¿
          </div>
        </div>
        <!--body-->
        <table
          border="0"
          width="100%"
          cellpadding="0"
          cellspacing="0"
          role="presentation"
          align="center">
          <tbody>
            <tr>
              <td
                style="margin-left:auto;margin-right:auto;margin-top:auto;margin-bottom:auto;background-color:rgb(255,255,255);font-family:&#x27;Alliance No1&#x27;, ui-sans-serif, system-ui, sans-serif, &#x27;Apple Color Emoji&#x27;, &#x27;Segoe UI Emoji&#x27;, &#x27;Segoe UI Symbol&#x27;, &#x27;Noto Color Emoji&#x27;">
                <table
                  align="center"
                  width="100%"
                  border="0"
                  cellpadding="0"
                  cellspacing="0"
                  role="presentation"
                  style="margin-left:auto;margin-right:auto;margin-top:80px;margin-bottom:80px;border-radius:0.5rem;border-width:1px;border-style:solid;border-color:rgb(232,231,228);padding-top:36px;padding-bottom:36px;padding-left:40px;padding-right:40px;background-color:rgb(255,255,255);max-width:37.5em">
                  <tbody>
                    <tr style="width:100%">
                      <td>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          class="">
                          <tbody>
                            <tr>
                              <td>
                                <img
                                  alt="Datum"
                                  height="70"
                                  src="https://www.datum.net/download/eng/logo-datum-light.png"
                                  style="margin-left:auto;margin-right:auto;margin-top:0;margin-bottom:0;display:block;outline:none;border:none;text-decoration:none" />
                                <hr
                                  style="margin-left:0;margin-right:0;margin-top:32px;margin-bottom:0;display:block;border-width:1px;border-color:rgb(232,231,228);border-style:solid;width:100%;border:none;border-top:1px solid #eaeaea" />
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          style="margin-top:32px;margin-bottom:32px">
                          <tbody>
                            <tr>
                              <td>
                                <table
                                  align="center"
                                  width="100%"
                                  border="0"
                                  cellpadding="0"
                                  cellspacing="0"
                                  role="presentation">
                                  <tbody style="width:100%">
                                    <tr style="width:100%">
                                      <h4
                                        style="margin-top:0;font-weight:500;margin-bottom:16px">
                                        Hi
                                        <!-- -->{{.Name}}<!-- -->,
                                      </h4>
                                      <p
                                        style="font-size:14px;line-height:20px;margin:0;font-weight:300;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                        Good news, you&#x27;re off the waitlist!
                                        I&#x27;m excited to share what we&#x27;ve
                                        built (so far) with Datum Cloud and get your
                                        feedback. To get started, just login below:
                                      </p>
                                      <a
                                        href="{{.ActionUrl}}"
                                        style="border-radius:0.25rem;font-weight:600;text-align:center;text-decoration-line:none;border-width:1px;border-style:solid;display:block;background-color:rgb(191,149,149);color:rgb(255,255,255);border-color:rgb(191,149,149);padding-left:20px;padding-right:20px;padding-top:12px;padding-bottom:12px;font-size:14px;line-height:20px;margin-top:24px;margin-bottom:24px;text-decoration:none;max-width:100%;mso-padding-alt:0px"
                                        target="_blank"
                                        ><span
                                          ><!--[if mso]><i style="mso-font-width:500%;mso-text-raise:18" hidden>&#8202;&#8202;</i><![endif]--></span
                                        ><span
                                          style="max-width:100%;display:inline-block;line-height:120%;mso-padding-alt:0px;mso-text-raise:9px"
                                          >Start building</span
                                        ><span
                                          ><!--[if mso]><i style="mso-font-width:500%" hidden>&#8202;&#8202;&#8203;</i><![endif]--></span
                                        ></a
                                      >
                                      <p
                                        style="font-size:14px;line-height:20px;margin:0;font-weight:300;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                        We&#x27;re releasing new features each week
                                        and chatting about issues and opportunities
                                        on Discord. Feel free to join me there with
                                        any questions or feedback.
                                      </p>
                                      <p
                                        style="font-size:14px;line-height:20px;margin-top:16px;margin-bottom:0;font-weight:300">
                                        Cheers,<br /><br />Zac Smith<br />Co-founder
                                        &amp; CEO at Datum
                                      </p>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          class="">
                          <tbody>
                            <tr>
                              <td>
                                <hr
                                  style="margin-left:0;margin-right:0;margin-bottom:32px;margin-top:0;display:block;border-width:1px;border-color:rgb(232,231,228);border-style:solid;width:100%;border:none;border-top:1px solid #eaeaea" />
                                <p
                                  style="font-size:14px;line-height:20px;margin:0;font-weight:300;margin-bottom:24px;margin-top:0;margin-left:0;margin-right:0">
                                  Datum unlocks cloud superpowers, without getting
                                  in the way. Find out more about Datum at<!-- -->
                                  <a
                                    href="https://www.datum.net"
                                    style="font-size:14px;line-height:20px;font-weight:300;text-decoration-line:underline;color:rgb(191,149,149)"
                                    target="_blank"
                                    >datum.net</a
                                  >
                                </p>
                                <table
                                  align="center"
                                  width="100%"
                                  border="0"
                                  cellpadding="0"
                                  cellspacing="0"
                                  role="presentation"
                                  style="margin-top:24px;margin-bottom:24px;display:table-cell;height:44px;width:56px">
                                  <tbody style="width:100%">
                                    <tr style="width:100%">
                                      <td
                                        data-id="__react-email-column"
                                        style="padding-right:8px">
                                        <a
                                          href="https://github.com/datum-cloud"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="GitHub"
                                            height="18"
                                            src="https://www.datum.net/download/eng/social-gh.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="18"
                                        /></a>
                                      </td>
                                      <td data-id="__react-email-column">
                                        <a
                                          href="https://www.linkedin.com/company/datum-cloud"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="LinkedIn"
                                            height="18"
                                            src="https://www.datum.net/download/eng/social-li.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="18"
                                        /></a>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                                <p
                                  style="font-size:14px;line-height:20px;margin:0;font-weight:300;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                  Datum Technology Inc. <br />29 Broadway <br />New
                                  York City <br />NY, 10006
                                </p>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
        <!--/$-->
      </body>
    </html>
    

  textBody: |
    ----------------------------------------
    
    HI {{.Name}},
    
    Good news, you're off the waitlist! I'm excited to share what we've built (so far) with Datum Cloud and get your feedback. To get started, just login below:
    
    Start building {{.ActionUrl}}
    
    We're releasing new features each week and chatting about issues and opportunities on Discord. Feel free to join me there with any questions or feedback.
    
    Cheers,
    
    Zac Smith
    Co-founder & CEO at Datum
    
    ----------------------------------------
    
    Datum unlocks cloud superpowers, without getting in the way. Find out more about Datum at datum.net https://www.datum.net
    
    https://github.com/datum-cloud https://www.linkedin.com/company/datum-cloud
    
    Datum Technology Inc.
    29 Broadway
    New York City
    NY, 10006

  variables:
  - name: "Name"
    required: true
    type: "string"
  - name: "ActionUrl"
    required: true
    type: "string"