apiVersion: notification.miloapis.com/v1alpha1
kind: EmailTemplate
metadata:
  name: emailtemplates.notification.miloapis.com-userwelcomeemailtemplate
spec:
  subject: "{{.UserName}} Welcome to Datum!"
  htmlBody: |
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html dir="ltr" lang="en">
      <head>
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/logo-datum-light.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-dt.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-dc.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-gh.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-yt.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-li.png" />
        <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
        <meta name="x-apple-disable-message-reformatting" />
      </head>
      <body
        style="background-color:rgb(255,255,255);margin-top:0;margin-bottom:0;margin-right:0;margin-left:0">
        <!--$--><!--html--><!--head-->
        <div
          style="display:none;overflow:hidden;line-height:1px;opacity:0;max-height:0;max-width:0"
          data-skip-in-text="true">
          {{.UserName}} Welcome to Datum!
          <div>
             ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿
          </div>
        </div>
        <!--body-->
        <table
          border="0"
          width="100%"
          cellpadding="0"
          cellspacing="0"
          role="presentation"
          align="center">
          <tbody>
            <tr>
              <td
                style='margin-right:auto;margin-left:auto;margin-bottom:auto;margin-top:auto;background-color:rgb(255,255,255);font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:rgb(12,29,49)'>
                <table
                  align="center"
                  width="100%"
                  border="0"
                  cellpadding="0"
                  cellspacing="0"
                  role="presentation"
                  style="max-width:600px;margin-right:auto;margin-left:auto;margin-bottom:80px;margin-top:80px;border-radius:0.5rem;border-style:solid;border-width:1px;border-color:rgb(232,231,228);padding-top:36px;padding-bottom:55px;padding-right:52px;padding-left:52px;background-color:rgb(255,255,255)">
                  <tbody>
                    <tr style="width:100%">
                      <td>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          class="">
                          <tbody>
                            <tr>
                              <td>
                                <img
                                  alt="Datum"
                                  height="70"
                                  src="https://www.datum.net/download/eng/logo-datum-light.png"
                                  style="display:block;outline:none;border:none;text-decoration:none;margin-right:auto;margin-left:auto;margin-bottom:0;margin-top:0" />
                                <hr
                                  style="width:100%;border:none;border-top:1px solid #eaeaea;margin-right:0;margin-left:0;margin-top:38px;margin-bottom:0;display:block;border-style:solid;border-width:1px;border-color:rgb(232,231,228)" />
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          style="margin-bottom:42px;margin-top:42px">
                          <tbody>
                            <tr>
                              <td>
                                <table
                                  align="center"
                                  width="100%"
                                  border="0"
                                  cellpadding="0"
                                  cellspacing="0"
                                  role="presentation">
                                  <tbody style="width:100%">
                                    <tr style="width:100%">
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:22px;font-weight:500">
                                        Hey
                                        <!-- -->{{.UserName}}<!-- -->,
                                        welcome to Datum! We&#x27;re glad
                                        you&#x27;re here.
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:22px;font-weight:400">
                                        Datum is building for a future that is
                                        evolving in front of our eyes, so we&#x27;re
                                        shipping updates all the time. We&#x27;re
                                        also serious about making improvements based
                                        on feedback, so if you&#x27;ve got some for
                                        us (good, bad, ugly) we&#x27;d love to have
                                        it.
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:22px;font-weight:400">
                                        Here&#x27;s how to stay in the loop, get
                                        help, or get involved:
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:8px;font-weight:400">
                                        <span style="font-weight:600">Email</span> –
                                        Respond to this note and we&#x27;ll get back
                                        to you
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:8px;font-weight:400">
                                        <a
                                          href="https://link.datum.net/discord"
                                          style="color:rgb(191,149,149);text-decoration-line:underline;font-weight:600"
                                          target="_blank"
                                          >Discord</a
                                        >
                                        <!-- -->– Join for support and connect with
                                        other builders
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:8px;font-weight:400">
                                        <a
                                          href="https://link.datum.net/events"
                                          style="color:rgb(191,149,149);text-decoration-line:underline;font-weight:600"
                                          target="_blank"
                                          >Luma</a
                                        >
                                        <!-- -->– Know when and where to meet us in
                                        person
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:8px;font-weight:400">
                                        <a
                                          href="https://link.datum.net/discussions"
                                          style="color:rgb(191,149,149);text-decoration-line:underline;font-weight:600"
                                          target="_blank"
                                          >GitHub Discussions</a
                                        >
                                        <!-- -->– Submit feedback, report issues, or
                                        request &amp; upvote features
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:0;font-weight:400">
                                        <a
                                          href="https://link.datum.net/careers"
                                          style="color:rgb(191,149,149);text-decoration-line:underline;font-weight:600"
                                          target="_blank"
                                          >Careers</a
                                        >
                                        <!-- -->– We&#x27;re actively hiring, and
                                        value folks spreading the word
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;font-weight:400;margin-top:22px;margin-bottom:0">
                                        ❤️<br />The Team at Datum
                                      </p>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          class="">
                          <tbody>
                            <tr>
                              <td>
                                <hr
                                  style="width:100%;border:none;border-top:1px solid #eaeaea;margin-right:0;margin-left:0;margin-bottom:37px;margin-top:0;display:block;border-style:solid;border-width:1px;border-color:rgb(232,231,228)" />
                                <table
                                  align="center"
                                  width="100%"
                                  border="0"
                                  cellpadding="0"
                                  cellspacing="0"
                                  role="presentation"
                                  style="display:table-cell;height:22px;width:56px">
                                  <tbody style="width:100%">
                                    <tr style="width:100%">
                                      <td
                                        data-id="__react-email-column"
                                        style="padding-right:15px">
                                        <a
                                          href="https://www.datum.net"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="Datum"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-dt.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                      <td
                                        data-id="__react-email-column"
                                        style="padding-right:15px">
                                        <a
                                          href="https://link.datum.net/discord"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="Discord"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-dc.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                      <td
                                        data-id="__react-email-column"
                                        style="padding-right:15px">
                                        <a
                                          href="https://link.datum.net/github"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="GitHub"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-gh.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                      <td
                                        data-id="__react-email-column"
                                        style="padding-right:15px">
                                        <a
                                          href="https://link.datum.net/youtube"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="YouTube"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-yt.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                      <td data-id="__react-email-column">
                                        <a
                                          href="https://link.datum.net/linkedin"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="LinkedIn"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-li.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                                <p
                                  style="font-size:13px;line-height:20px;margin:0;font-weight:400;margin-top:29px;margin-bottom:0;margin-left:0;margin-right:0">
                                  Datum Technology Inc. <br />120 Broadway, 26th
                                  Floor <br />New York, NY 10271
                                </p>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
        <!--/$-->
      </body>
    </html>
    

  textBody: |
    ----------------------------------------
    
    Hey {{.UserName}}, welcome to Datum! We're glad you're here.
    
    Datum is building for a future that is evolving in front of our eyes, so we're shipping updates all the time. We're also serious about making improvements based on feedback, so if you've got some for us (good, bad, ugly) we'd love to have it.
    
    Here's how to stay in the loop, get help, or get involved:
    
    Email – Respond to this note and we'll get back to you
    
    Discord https://link.datum.net/discord – Join for support and connect with other builders
    
    Luma https://link.datum.net/events – Know when and where to meet us in person
    
    GitHub Discussions https://link.datum.net/discussions – Submit feedback, report issues, or request & upvote features
    
    Careers https://link.datum.net/careers – We're actively hiring, and value folks spreading the word
    
    ❤️
    The Team at Datum
    
    ----------------------------------------
    
    https://www.datum.net https://link.datum.net/discord https://link.datum.net/github https://link.datum.net/youtube https://link.datum.net/linkedin
    
    Datum Technology Inc.
    120 Broadway, 26th Floor
    New York, NY 10271

  variables:
  - name: "UserName"
    required: true
    type: "string"