apiVersion: notification.miloapis.com/v1alpha1
kind: EmailTemplate
metadata:
  name: emailtemplates.notification.miloapis.com-userinvitationemailtemplate
spec:
  subject: "Invitation to collaborate at Datum"
  htmlBody: |
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html dir="ltr" lang="en">
      <head>
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/logo-datum-light.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-dt.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-dc.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-gh.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-yt.png" />
        <link
          rel="preload"
          as="image"
          href="https://www.datum.net/download/eng/social-li.png" />
        <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
        <meta name="x-apple-disable-message-reformatting" />
      </head>
      <body
        style="background-color:rgb(255,255,255);margin-top:0;margin-bottom:0;margin-right:0;margin-left:0">
        <!--$--><!--html--><!--head-->
        <div
          style="display:none;overflow:hidden;line-height:1px;opacity:0;max-height:0;max-width:0"
          data-skip-in-text="true">
          {{.InviterDisplayName}} invited you to join
          {{.OrganizationDisplayName}}
          <div>
             ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿ ‌​‍‎‏﻿
          </div>
        </div>
        <!--body-->
        <table
          border="0"
          width="100%"
          cellpadding="0"
          cellspacing="0"
          role="presentation"
          align="center">
          <tbody>
            <tr>
              <td
                style='margin-right:auto;margin-left:auto;margin-bottom:auto;margin-top:auto;background-color:rgb(255,255,255);font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:rgb(12,29,49)'>
                <table
                  align="center"
                  width="100%"
                  border="0"
                  cellpadding="0"
                  cellspacing="0"
                  role="presentation"
                  style="max-width:600px;margin-right:auto;margin-left:auto;margin-bottom:80px;margin-top:80px;border-radius:0.5rem;border-style:solid;border-width:1px;border-color:rgb(232,231,228);padding-top:36px;padding-bottom:55px;padding-right:52px;padding-left:52px;background-color:rgb(255,255,255)">
                  <tbody>
                    <tr style="width:100%">
                      <td>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          class="">
                          <tbody>
                            <tr>
                              <td>
                                <img
                                  alt="Datum"
                                  height="70"
                                  src="https://www.datum.net/download/eng/logo-datum-light.png"
                                  style="display:block;outline:none;border:none;text-decoration:none;margin-right:auto;margin-left:auto;margin-bottom:0;margin-top:0" />
                                <hr
                                  style="width:100%;border:none;border-top:1px solid #eaeaea;margin-right:0;margin-left:0;margin-top:38px;margin-bottom:0;display:block;border-style:solid;border-width:1px;border-color:rgb(232,231,228)" />
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          style="margin-bottom:42px;margin-top:42px">
                          <tbody>
                            <tr>
                              <td>
                                <table
                                  align="center"
                                  width="100%"
                                  border="0"
                                  cellpadding="0"
                                  cellspacing="0"
                                  role="presentation">
                                  <tbody style="width:100%">
                                    <tr style="width:100%">
                                      <p
                                        style="font-size:28px;line-height:40px;margin-top:0;margin-bottom:22px;font-weight:500">
                                        Hey there!
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin-top:0;margin-bottom:22px;font-weight:400">
                                        {{.InviterDisplayName}}<!-- -->
                                        has invited you to join the<!-- -->
                                        <!-- -->{{.OrganizationDisplayName}}<!-- -->
                                        organization at Datum.
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin:0;font-weight:400;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                        Please click the button to set up your
                                        account and get started. If you need help,
                                        just reply to this email or visit us on<!-- -->
                                        <a
                                          href="https://link.datum.net/discord"
                                          style="color:rgb(191,149,149);text-decoration-line:underline"
                                          target="_blank"
                                          >Discord</a
                                        >.
                                      </p>
                                      <a
                                        href="https://cloud.datum.net/invitation/{{.UserInvitationName}}/accept"
                                        style="line-height:20px;text-decoration:none;display:block;max-width:100%;mso-padding-alt:0px;border-radius:0.25rem;font-weight:600;text-align:center;text-decoration-line:none;border-style:solid;border-width:1px;background-color:rgb(191,149,149);color:rgb(255,255,255);border-color:rgb(191,149,149);padding-right:24px;padding-left:24px;padding-bottom:14px;padding-top:14px;font-size:16px;margin-top:36px;margin-bottom:32px"
                                        target="_blank"
                                        ><span
                                          ><!--[if mso
                                            ]><i
                                              style="mso-font-width:400%;mso-text-raise:21"
                                              hidden
                                              >&#8202;&#8202;&#8202;</i
                                            ><!
                                          [endif]--></span
                                        ><span
                                          style="max-width:100%;display:inline-block;line-height:120%;mso-padding-alt:0px;mso-text-raise:10.5px"
                                          >Accept invitation</span
                                        ><span
                                          ><!--[if mso
                                            ]><i style="mso-font-width:400%" hidden
                                              >&#8202;&#8202;&#8202;&#8203;</i
                                            ><!
                                          [endif]--></span
                                        ></a
                                      >
                                      <p
                                        style="font-size:13px;line-height:20px;font-weight:400;margin-top:16px;margin-bottom:16px">
                                        Or you can copy and paste the following URL
                                        into your browser:<!-- -->
                                        <a
                                          href="https://cloud.datum.net/invitation/{{.UserInvitationName}}/accept"
                                          style="color:rgb(191,149,149);text-decoration-line:underline"
                                          target="_blank"
                                          >https://cloud.datum.net/invitation/<!-- -->{{.UserInvitationName}}<!-- -->/accept</a
                                        >
                                      </p>
                                    </tr>
                                  </tbody>
                                </table>
                                <table
                                  align="center"
                                  width="100%"
                                  border="0"
                                  cellpadding="0"
                                  cellspacing="0"
                                  role="presentation">
                                  <tbody style="width:100%">
                                    <tr style="width:100%">
                                      <hr
                                        style="width:100%;border:none;border-top:1px solid #eaeaea;margin-right:0;margin-left:0;margin-bottom:42px;margin-top:42px;display:block;border-style:solid;border-width:1px;border-color:rgb(232,231,228)" />
                                      <p
                                        style="font-size:21px;line-height:28px;margin-top:0;font-weight:600;margin-bottom:11px">
                                        Why Datum?
                                      </p>
                                      <p
                                        style="font-size:17px;line-height:24px;margin:0;font-weight:400;margin-top:0;margin-bottom:0;margin-left:0;margin-right:0">
                                        Datum is a venture-backed startup based in
                                        New York City. Our mission is to help 1k new
                                        clouds thrive in the age of AI by unlocking
                                        internet superpowers for every builder.
                                      </p>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table
                          align="center"
                          width="100%"
                          border="0"
                          cellpadding="0"
                          cellspacing="0"
                          role="presentation"
                          class="">
                          <tbody>
                            <tr>
                              <td>
                                <hr
                                  style="width:100%;border:none;border-top:1px solid #eaeaea;margin-right:0;margin-left:0;margin-bottom:37px;margin-top:0;display:block;border-style:solid;border-width:1px;border-color:rgb(232,231,228)" />
                                <table
                                  align="center"
                                  width="100%"
                                  border="0"
                                  cellpadding="0"
                                  cellspacing="0"
                                  role="presentation"
                                  style="display:table-cell;height:22px;width:56px">
                                  <tbody style="width:100%">
                                    <tr style="width:100%">
                                      <td
                                        data-id="__react-email-column"
                                        style="padding-right:15px">
                                        <a
                                          href="https://www.datum.net"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="Datum"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-dt.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                      <td
                                        data-id="__react-email-column"
                                        style="padding-right:15px">
                                        <a
                                          href="https://link.datum.net/discord"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="Discord"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-dc.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                      <td
                                        data-id="__react-email-column"
                                        style="padding-right:15px">
                                        <a
                                          href="https://link.datum.net/github"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="GitHub"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-gh.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                      <td
                                        data-id="__react-email-column"
                                        style="padding-right:15px">
                                        <a
                                          href="https://link.datum.net/youtube"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="YouTube"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-yt.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                      <td data-id="__react-email-column">
                                        <a
                                          href="https://link.datum.net/linkedin"
                                          style="color:#067df7;text-decoration-line:none"
                                          target="_blank"
                                          ><img
                                            alt="LinkedIn"
                                            height="22"
                                            src="https://www.datum.net/download/eng/social-li.png"
                                            style="display:block;outline:none;border:none;text-decoration:none"
                                            width="22"
                                        /></a>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                                <p
                                  style="font-size:13px;line-height:20px;margin:0;font-weight:400;margin-top:29px;margin-bottom:0;margin-left:0;margin-right:0">
                                  Datum Technology Inc. <br />120 Broadway, 26th
                                  Floor <br />New York, NY 10271
                                </p>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
        <!--/$-->
      </body>
    </html>
    

  textBody: |
    ----------------------------------------
    
    Hey there!
    
    {{.InviterDisplayName}} has invited you to join the {{.OrganizationDisplayName}} organization at Datum.
    
    Please click the button to set up your account and get started. If you need help, just reply to this email or visit us on Discord https://link.datum.net/discord.
    
    Accept invitation https://cloud.datum.net/invitation/{{.UserInvitationName}}/accept
    
    Or you can copy and paste the following URL into your browser: https://cloud.datum.net/invitation/{{.UserInvitationName}}/accept
    
    ----------------------------------------
    
    Why Datum?
    
    Datum is a venture-backed startup based in New York City. Our mission is to help 1k new clouds thrive in the age of AI by unlocking internet superpowers for every builder.
    
    ----------------------------------------
    
    https://www.datum.net https://link.datum.net/discord https://link.datum.net/github https://link.datum.net/youtube https://link.datum.net/linkedin
    
    Datum Technology Inc.
    120 Broadway, 26th Floor
    New York, NY 10271

  variables:
  - name: "InviterDisplayName"
    required: true
    type: "string"
  - name: "OrganizationDisplayName"
    required: true
    type: "string"
  - name: "UserInvitationName"
    required: true
    type: "string"